// <auto-generated />
namespace HSNHospitalProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changerecorddatetype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changerecorddatetype));
        
        string IMigrationMetadata.Id
        {
            get { return "202004022230395_change-recorddate-type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
